In [16]:
import pandas as pd
from scipy import stats

In [17]:
dfs = pd.read_excel(r'data.xlsx')[:-1]
#dfs.drop(dfs[:,6:])
dfs

,spy,govt,eemv,acn,br,cboe,cme,ice,spy_r,govt_r,eemv_r,acn_r,br_r,cboe_r,cme_r,ice_r
0,158.535507,21.473974,47.697281,70.912788,33.942150,46.627060,57.320522,40.378170,-0.035248,0.012346,-0.081359,-0.028460,-0.081731,0.001155,-0.047158,-0.071715
1,152.947403,21.739086,43.816658,68.894592,31.168037,46.680904,54.617428,37.482456,0.045516,0.002970,0.035874,0.043440,0.040507,0.042122,-0.012574,0.000240
2,159.908920,21.803652,45.388557,71.887398,32.430561,48.647186,53.930687,37.491451,0.008296,-0.004020,0.031746,-0.043551,-0.010994,0.047566,0.008914,-0.049767
3,161.235458,21.716003,46.829464,68.756599,32.074013,50.961143,54.411430,35.625629,0.006951,0.007508,0.018182,0.018369,0.032310,-0.057244,-0.049041,0.033413
4,162.356277,21.879057,47.680912,70.019585,33.110340,48.043941,51.743065,36.815971,0.023207,0.007907,0.023351,0.015333,0.069901,-0.046850,0.022873,-0.039327
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,447.153015,26.681725,63.051403,334.696014,170.204010,125.680168,196.279785,118.561249,-0.046605,-0.010702,-0.018942,-0.049441,-0.028751,-0.018153,-0.036871,-0.036739
93,426.313232,26.396172,61.857094,318.148193,165.310532,123.398697,189.042847,114.205437,0.070163,-0.000717,0.004787,0.124829,0.070631,0.065235,0.140501,0.205888
94,456.224854,26.377251,62.153206,357.862213,176.986649,131.448608,215.603485,137.718918,-0.008035,0.006083,-0.015563,-0.003874,-0.055154,-0.019084,-0.000136,-0.055901
95,452.559204,26.537691,61.185921,356.475800,167.225159,128.940002,215.574158,130.020325,0.046248,0.003615,0.026707,0.159905,0.088418,0.011323,0.055016,0.048844
96,473.489044,26.633615,62.820000,413.477997,182.010849,130.399994,227.434280,136.371017,-0.052741,-0.026237,-0.005890,-0.144864,-0.129089,-0.091028,0.004552,-0.073920

In [18]:
###arithmatic mean
(dfs.mean())[-8:]

spy_r     0.011577
govt_r    0.002009
eemv_r    0.003444
acn_r     0.018421
br_r      0.017721
cboe_r    0.011821
cme_r     0.015792
ice_r     0.013322
dtype: float64

In [19]:
(dfs.std())[-8:]

spy_r     0.040117
govt_r    0.011159
eemv_r    0.036398
acn_r     0.059091
br_r      0.059232
cboe_r    0.065333
cme_r     0.054294
ice_r     0.055712
dtype: float64

In [20]:
new = dfs.iloc[:,-8:]+1
new

,spy_r,govt_r,eemv_r,acn_r,br_r,cboe_r,cme_r,ice_r
0,0.964752,1.012346,0.918641,0.971540,0.918269,1.001155,0.952842,0.928285
1,1.045516,1.002970,1.035874,1.043440,1.040507,1.042122,0.987426,1.000240
2,1.008296,0.995980,1.031746,0.956449,0.989006,1.047566,1.008914,0.950233
3,1.006951,1.007508,1.018182,1.018369,1.032310,0.942756,0.950959,1.033413
4,1.023207,1.007907,1.023351,1.015333,1.069901,0.953150,1.022873,0.960673
...,...,...,...,...,...,...,...,...
92,0.953395,0.989298,0.981058,0.950559,0.971249,0.981847,0.963129,0.963261
93,1.070163,0.999283,1.004787,1.124829,1.070631,1.065235,1.140501,1.205888
94,0.991965,1.006083,0.984437,0.996126,0.944846,0.980916,0.999864,0.944099
95,1.046248,1.003615,1.026707,1.159905,1.088418,1.011323,1.055016,1.048844
96,0.947259,0.973763,0.994110,0.855136,0.870911,0.908972,1.004552,0.926080

In [21]:
dfs.size
len(dfs)

97

In [22]:
len(dfs.columns)

16

In [23]:
new.spy_r.product()**(1/97)

1.0107789903096907

In [24]:
new.product()**(1/97) -1

spy_r     0.010779
govt_r    0.001948
eemv_r    0.002782
acn_r     0.016701
br_r      0.016015
cboe_r    0.009665
cme_r     0.014357
ice_r     0.011825
dtype: float64

In [25]:
(stats.gmean(new.spy_r)-1)*100

1.077899030969065

In [26]:
(stats.gmean(new.govt_r)-1)*100

0.19477215647512036

In [27]:
(stats.gmean(new.acn_r)-1)*100

1.670142948458575

In [28]:
#####geometric mean
(new.product()**(1/len(dfs))-1)

spy_r     0.010779
govt_r    0.001948
eemv_r    0.002782
acn_r     0.016701
br_r      0.016015
cboe_r    0.009665
cme_r     0.014357
ice_r     0.011825
dtype: float64

In [29]:
###covariance
dfs.iloc[:,-8:].cov()

,spy_r,govt_r,eemv_r,acn_r,br_r,cboe_r,cme_r,ice_r
spy_r,0.001609,-0.000114,0.001014,0.001893,0.001482,0.000940,0.000816,0.001274
govt_r,-0.000114,0.000125,-0.000057,-0.000061,0.000033,-0.000017,-0.000121,-0.000086
eemv_r,0.001014,-0.000057,0.001325,0.000926,0.000891,0.000323,0.000192,0.000392
acn_r,0.001893,-0.000061,0.000926,0.003492,0.002259,0.001281,0.001069,0.001869
br_r,0.001482,0.000033,0.000891,0.002259,0.003508,0.001046,0.001112,0.001446
cboe_r,0.000940,-0.000017,0.000323,0.001281,0.001046,0.004268,0.001924,0.001670
cme_r,0.000816,-0.000121,0.000192,0.001069,0.001112,0.001924,0.002948,0.001837
ice_r,0.001274,-0.000086,0.000392,0.001869,0.001446,0.001670,0.001837,0.003104

In [30]:
dfs.iloc[:,-8:-5].cov()

           spy_r    govt_r    eemv_r
spy_r   0.001609 -0.000114  0.001014
govt_r -0.000114  0.000125 -0.000057
eemv_r  0.001014 -0.000057  0.001325